### ISSUE TITLE
Create FirmwareUpdater sample

### ISSUE THREAD

**Issue by SatjaSivcev** [zivid/zivid-csharp-samples#27]
Port https://github.com/zivid/cpp-extra-samples/blob/clang-tidy/source/Camera/InfoUtilOther/FirmwareUpdater/FirmwareUpdater.cpp  to C#

**Comment by TTPinto** [comment]
![image](https://user-images.githubusercontent.com/102810056/168644923-6ba6c4bc-ada4-460d-abe8-815ad7567f28.png)

**Comment by SatjaSivcev** [comment]
Fixed, see https://github.com/zivid/zivid-csharp-samples/blob/master/source/Camera/InfoUtilOther/FirmwareUpdater/FirmwareUpdater.cs
