### ISSUE TITLE
C# GetCameraIntrinsics | Return wrong value to console

### ISSUE THREAD

**Issue by KamleitnerLukas** [zivid/zivid-csharp-samples#51]
Hello,

in line 33 and 34 is the wrong property retuned to console, I think.

33 Console.WriteLine("    **P1** = " + intrinsics.Distortion.**K1**.ToString());
34 Console.WriteLine("    **P2** = " + intrinsics.Distortion.**K2**.ToString());

**Comment by SatjaSivcev** [comment]
Fixed, see https://github.com/zivid/zivid-csharp-samples/blob/master/source/Camera/InfoUtilOther/GetCameraIntrinsics/GetCameraIntrinsics.cs
